### ISSUE TITLE
Add support to parse Fortran array bounds with expressions

### ISSUE THREAD

**Issue by sergisiso** [stfc/PSyclone#2138] opened 2023-05-11 15:12 UTC
For example: `real :: a(start - 1: stop + 1)`

Currently it is a UnknownFortranType, but it should be an ArrayType with an ArrayBound with 2 psyir expressions.

**Comment by arporter** [comment] 2024-03-07 09:51
This is also an issue when attempting to inline routines/functions in NEMO (e.g. snw_ent in icethd_dh.f90).

**Comment by arporter** [comment] 2024-04-23 08:12
I shall take this one on.

**Comment by arporter** [comment] 2024-04-23 14:22
It turns out this is a duplicate of #947 but as I've only just discovered this, I'll carry on with this one.

**Comment by arporter** [comment] 2024-07-01 10:09
When processing declarations, we do any derived types first. So, in the following we are parsing `vbig_type` *before*
we have created a symbol for `ngrids`:
```
module test_mod
  integer, parameter :: ngrids = 10
  type vbig_type
      type(big_type), dimension(ngrids) :: grids
   end type vbig_type
end module
```
Unfortunately, when parsing a derived-type, we use a temporary Symbol Table to collect its members and therefore we end up putting a symbol for `ngrids` into that table. This will then *not* be the Symbol we create when we come to process the original declaration of `ngrids`.

**Closed** 2024-07-11 10:59 UTC
Labels: in progress, NEMO, CROCO
