### ISSUE TITLE
PSyclone not handling Use re-name symbols correctly

### ISSUE THREAD

**Issue by LonelyCat124** [stfc/PSyclone#2206] opened 2023-06-30 13:21 UTC
The `socrates_runes.f90` file contains a `Use` statement that does renaming, and PSyclone is outputting Fortran without these renamings:
This:
```
use rad_pcf, only: &
  ip_source_illuminate                      => ip_solar, &
  ip_source_thermal                         => ip_infra_red, &
  ip_cloud_representation_off               => ip_cloud_off, &
  ip_cloud_representation_ice_water         => ip_cloud_ice_water, &
  ip_cloud_representation_combine_ice_water => ip_cloud_combine_ice_water, &
  ip_cloud_representation_csiw              => ip_cloud_csiw, &
  ip_cloud_representation_split_ice_water   => ip_cloud_split_ice_water, &
  ip_overlap_max_random                     => ip_max_rand, &
  ip_overlap_random                         => ip_rand, &
  ip_overlap_exponential_random             => ip_exponential_rand, &
  ip_inhom_homogeneous                      => ip_homogeneous, &
  ip_inhom_scaling                          => ip_scaling, &
  ip_inhom_mcica                            => ip_mcica, &
  ip_inhom_cairns                           => ip_cairns, &
  ip_inhom_tripleclouds_2019                => ip_tripleclouds_2019, &
  ip_droplet_re_external                    => ip_re_external, &
  ip_droplet_re_constant                    => ip_re_constant, &
  ip_droplet_re_liu                         => ip_re_liu, &
  ip_droplet_re_default                     => ip_re_default
```
is converted to this by PSyclone:
```
  use rad_pcf, only : ip_cloud_representation_combine_ice_water, ip_cloud_representation_csiw, ip_cloud_representation_ice_water, &
&ip_cloud_representation_off, ip_cloud_representation_split_ice_water, ip_droplet_re_constant, ip_droplet_re_default, &
&ip_droplet_re_external, ip_droplet_re_liu, ip_inhom_cairns, ip_inhom_homogeneous, ip_inhom_mcica, ip_inhom_scaling, &
&ip_inhom_tripleclouds_2019, ip_overlap_exponential_random, ip_overlap_max_random, ip_overlap_random, ip_source_illuminate, &
&ip_source_thermal
```

This then fails to compile as the compiler looks in the module for these variables but fails to find them.

**Comment by LonelyCat124** [comment] 2023-06-30 13:30
Mini test-case:
```
def test_fail_case(fortran_reader, fortran_writer):
    code = '''
    module a
    integer, parameter :: a_mod_name = 2
    end module a
    module b
    use a, only: b_mod_name => a_mod_name
    contains
    subroutine X()
       print *, b_mod_name
    end subroutine X
    end module b
    '''
    psyir = fortran_reader.psyir_from_source(code)
    output = fortran_writer(psyir)
    assert "=>" in output
```

**Comment by arporter** [comment] 2023-06-30 14:57
This may be a duplicate of #2196. The latter has the 'intrinsic' qualifier on the USE statement though.

**Comment by LonelyCat124** [comment] 2023-07-03 15:36
Having a quick look at this (not sure i'll find the solution right now though).

The test does correctly find the `orig_name` in `fparser.py` - adding `print(sym_name, orig_name)` shows: `b_mod_name a_mod_name`. This is no longer visible in the fortran backend.
This seems to make it into the creation of the Symbol correctly (I can see orig name inside `_process_arguments`).

When I print `psyir.children[1].symbol_table` I still get `b_mod_name: Symbol<Import(container='a', orig_name='a_mod_name')>` so this is probably a bug in the `fortran_writer`.

When I check in `container_node` the info about the original name is no longer present.

What I believe is happening is during lowering of some node we're losing this information. I added these prints in `visitor.py:__call__`:
```
        try:
            for child in node.children:
                print(child.symbol_table)                                                                                                                                              lowered_node = node_copy.lower_to_language_level()
            for child in lowered_node.children:
                print(child.symbol_table
```

The output from this is:
```
Symbol Table of Container 'a':
------------------------------
a_mod_name: DataSymbol<Scalar<INTEGER, UNDEFINED>, DefaultModule, constant_value=Literal[value:'2', Scalar<INTEGER, UNDEFINED>]>

Symbol Table of Container 'b':
------------------------------
x: RoutineSymbol<NoType, pure=False, elemental=False>
a: ContainerSymbol<not linked>
b_mod_name: Symbol<Import(container='a', orig_name='a_mod_name')>

Symbol Table of Container 'a':
------------------------------
a_mod_name: DataSymbol<Scalar<INTEGER, UNDEFINED>, DefaultModule, constant_value=Literal[value:'2', Scalar<INTEGER, UNDEFINED>]>

Symbol Table of Container 'b':
------------------------------
x: RoutineSymbol<NoType, pure=unknown, elemental=unknown>
a: ContainerSymbol<not linked>
b_mod_name: Symbol<Import(container='a')>`
```
It seems pretty clear that this info is being discarded somehow during lowering.

**Comment by LonelyCat124** [comment] 2023-07-03 15:51
To avoid continued rambling comment, I found where its dissapearing.

In `ScopingNode` `_refine_copy` there is a call to `self._symbol_table = other.symbol_table.deep_copy()`

Adding prints around this gives:
```
Symbol Table of Container 'b':
------------------------------
x: RoutineSymbol<NoType, pure=False, elemental=False>
a: ContainerSymbol<not linked>
b_mod_name: Symbol<Import(container='a', orig_name='a_mod_name')>

Symbol Table:
-------------
x: RoutineSymbol<NoType, pure=unknown, elemental=unknown>
a: ContainerSymbol<not linked>
b_mod_name: Symbol<Import(container='a')>
```

chasing this down to `symbol.interface = ImportInterface(new_container)` which is where it dissapears.

I don't think this change alone will fix `intrinsic` going missing, but should give you a decent idea what to look for @arporter 

I will push a fix for this I think.

**Closed** 2023-07-04 14:05 UTC
Labels: bug, socrates
