### ISSUE TITLE
PSYKE: Generate a Driver layer

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#298] opened 2019-02-15 16:58 UTC
Issue #139 and associated PR #218 introduced functionality to mark Nodes for code extraction, without and with optimisations. This issue builds PSyclone structures for generation of a Driver layer to run the extracted code.

**Comment by hiker** [comment] 2024-01-30 11:27
This is a duplicate of #1392 , which is already closed.

**Closed by hiker** 2024-01-30 11:27 UTC
Labels: enhancement, LFRic
