### ISSUE TITLE
Improve Test Coverage 

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#1861] opened 2022-09-09 06:15 UTC
Especially the compile part of the utilities has a very low coverage (since the tests are run with compilation disabled). This can be improved by using 'true' or 'false' as the 'compiler'.

**Comment by arporter** [comment] 2022-09-16 10:18
I think #1199 is a duplicate of this? If so @hiker I will close it as I've not done any work on it.

**Comment by hiker** [comment] 2022-09-16 13:26
> I think #1199 is a duplicate of this? If so @hiker I will close it as I've not done any work on it.

Yes, pretty much (sorry, I didn't notice). #1199 also mentioned 'a  bit of logging', but I believe that is kind of happening (if you specify `-s` in pytest) - though you then typically get flooded with way too may messages, since each infrastructure file is reported). I'll just save you the trouble and close it.

**Comment by arporter** [comment] 2022-10-19 15:56
#1867 is on master now.

**Closed by arporter** 2022-10-19 15:56 UTC
Labels: enhancement, in progress
