### ISSUE TITLE
Graphviz Test Failures on master

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#473] opened 2019-08-21 05:30 UTC
I am getting graphviz/dag related test failures on master:
```
# linux-atdw:~/work/psyclone >
pytest -s -k test_writetoread_dag ./src/psyclone/tests/gocean1p0_test.py
=========================================================================================================== test session starts ============================================================================================================
platform linux -- Python 3.6.5, pytest-4.5.0, py-1.5.2, pluggy-0.11.0
rootdir: /home/joergh/work/psyclone, inifile: setup.cfg
plugins: xdist-1.28.0, forked-1.0.2
collected 49 items / 48 deselected / 1 selected                                                                                                                                                                                            

src/psyclone/tests/gocean1p0_test.py F

================================================================================================================= FAILURES =================================================================================================================
___________________________________________________________________________________________________________ test_writetoread_dag ___________________________________________________________________________________________________________

tmpdir = local('/tmp/pytest-of-joergh/pytest-178/test_writetoread_dag0'), have_graphviz = True

    def test_writetoread_dag(tmpdir, have_graphviz):
        ''' Test that the GOInvokeSchedule::dag() method works as expected when we
        have two kernels with a write -> read dependency '''
        _, invoke_info = parse(os.path.join(os.path.
                                            dirname(os.path.
                                                    abspath(__file__)),
                                            "test_files", "gocean1p0",
                                            "single_invoke_write_to_read.f90"),
                               api=API)
        psy = PSyFactory(API).create(invoke_info)
        invoke = psy.invokes.invoke_list[0]
        old_cwd = tmpdir.chdir()
        invoke.schedule.dag()
        if have_graphviz:
            dot_file = os.path.join(str(tmpdir), "dag")
            assert os.path.isfile(dot_file)
            with open(dot_file, "r") as dfile:
                dot = dfile.read()
            assert dot.startswith("digraph")
            # write -> read means that the second loop can only begin once the
            # first loop is complete. Check that we have the correct forwards
            # dependence (green) and backwards dependence (red).
>           assert ('"loop_[outer]_1_end" -> "loop_[outer]_4_start" [color=red]'
                    in dot or
                    '"loop_[outer]_1_end" -> "loop_[outer]_4_start" '
                    '[color=#ff0000]' in dot)
E           assert ('"loop_[outer]_1_end" -> "loop_[outer]_4_start" [color=red]' in 'digraph {\n\tschedule_start\n\tschedule_end\n\t"loop_[outer]_1_start"\n\t"loop_[outer]_1_end"\n\t"loop_[outer]_1_end"...tkernel_compute_v_code_22 -> schedule_end [color=blue]\n\tschedule_start -> kernel_compute_v_code_22 [color=blue]\n}\n' or '"loop_[outer]_1_end" -> "loop_[outer]_4_start" [color=#ff0000]' in 'digraph {\n\tschedule_start\n\tschedule_end\n\t"loop_[outer]_1_start"\n\t"loop_[outer]_1_end"\n\t"loop_[outer]_1_end"...tkernel_compute_v_code_22 -> schedule_end [color=blue]\n\tschedule_start -> kernel_compute_v_code_22 [color=blue]\n}\n')

/home/joergh/work/psyclone/src/psyclone/tests/gocean1p0_test.py:1098: AssertionError
================================================================================================= 1 failed, 48 deselected in 0.49 seconds ==================================================================================================
```
And similar "-k test_writetoread_dag ./src/psyclone/testgocean1p0_test.py". Somehow git bisect failed to do its job (couldn't do a checkout due to files already in places???), and manually I made it all the way to pull request #400: 72f8da3afb8669ceba718495b3f920ac7d62daa0 works, but the next one 145c10678856a9fe2978b200879ce4a49717dc24 fails, which is a merge request

Now I _think_ ... that both branches that are merged are actually correct:
f4276f7dcf17df6f8dbf0c2e57c00a6612b45bf9  and 72f8da3afb8669ceba718495b3f920ac7d62daa0 both seems to work.

So, I'll leave it to someone who understands this better than me to fix :)

And maybe we want travis to test graphviz as well?

**Comment by arporter** [comment] 2019-09-09 12:11
I think this problem (which I can reproduce) is because our `Schedule` has gained new nodes - e.g. Loops now have their bounds as children. The resulting DAG output has quite a few `node_x` 'nodes' in it indicating that there are nodes in the Schedule that have not overridden `Node.dag_name` . This feels like something for @rupertford as he did this originally...

**Comment by arporter** [comment] 2019-09-09 12:13
Maybe it's at this point that we should (virtually) sit down and discuss what we want to do with the "PSy-layer" dependency analysis and Joerg's "Schedule" dependency analysis?

**Comment by hiker** [comment] 2019-10-28 11:11
OK, there are actually two problems:
1) the introduction of start/stop/step to the Loop node.
2) the introduction of the additional schedule node ( the dag_name of a schedule is just 'schedule', no abs_position --> every schedule that is in the tree uses the same node name 'schedule'.

Those schedule nodes are a big pain. I can get usable graphs if I:
1) ignore the first three entries of a loop (i.e. only use the body)
2) Add abs_position to each schedule's dag_name
See https://github.com/stfc/PSyclone/tree/473_fix_dag for details. And the 'fix' is not nice.

But even then the graphs are now (imho) unnecessary complicated - see below, and imagine schedules being added to the omp node :(

![dag](https://user-images.githubusercontent.com/6138652/67673107-6636f380-f9cd-11e9-8620-7aca9ec9ab8b.png)

Do you want me to fix up the test cases, and we accept more and more complex graphs showing schedules??

**Comment by rupertford** [comment] 2019-10-28 16:56
Sorry that I've been quiet on this issue. I can see @hiker's point about complexity with the extra Schedules. There is also @arporter's point about the dag view only being designed for "PSy" PSyIR and using the dependency analysis associated with this, c.f. the "kernel" PSyIR and the dependency analysis associated with that. I would also add that this is not actually a full dag view, it only provides a subset of the dependencies (the ones closest in the original schedule).

So, in the short term (i.e. this issue) I would say that to get this working again, ignoring the 3 entries in the loop is obviously needed. Regarding Schedules, they could be ignored and not output if that is preferred (apart from the root one), or, if not, they will need the global index, or similar identifier, to give a unique name, as you have done.

In the medium term I would say that we should think about what output is useful. I personally think a "proper" dag is a useful thing and I would suggest we create one using a new PSyIR backend combined with Joerg's dependence analysis code. This would currently only work for "kernel" PSyIR but when we remove the "gen" methods (and merge the dependency analysis) it should replace the current dag_gen and be used for all nodes.

I suspect that HPC experts would be interested in different views as well e.g. only the dependencies for a particular variable, or set of variables, but we can develop such things when there is a need/request for them.

**Comment by arporter** [comment] 2019-11-14 16:20
PR merged. Closing issue.

**Closed by arporter** 2019-11-14 16:20 UTC
Labels: bug
