### ISSUE TITLE
Hoisting automatic arrays in NEMO v4.2

### ISSUE THREAD

**Issue by deardenchris** [stfc/PSyclone#1969] opened 2022-11-28 15:24 UTC
In NEMO v4.2, the introduction of tiling in the lat-lon dimensions means that the declaration of automatic arrays is specified differently in the tracer, vertical diffusion and dynamics code sections. 

For example, previously in v4.0 we would have (in subroutine `tra_adv_fct`, module `traadv_fct.f90`):

`REAL(wp), DIMENSION(jpi, jpj, jpk) :: zwi, zwx, zwy, zwz, ztu, ztv, zltu, zltv, ztw`

Whereas in v4.2, this is now specified as:

` REAL(wp), DIMENSION(ntsi-(nn_hls):ntei+(nn_hls),ntsj-(nn_hls):ntej+(nn_hls),jpk) ::   zwi, zwx, zwy, zwz, ztu, ztv, zltu, zltv, ztw`

I've noticed that the `HoistLocalArraysTrans` transformation is unable to hoist automatic arrays that involve the tiling indices in their declaration. Specifically, the issue seems to be the use of `+/- nn_hls` when specifying the array ranges.

**Comment by arporter** [comment] 2022-12-12 16:47
This is essentially a duplicate of #1801 so I'm closing this.

**Closed by arporter** 2022-12-12 16:47 UTC
Labels: enhancement, NEMO
