### ISSUE TITLE
Add PSyData_Start and PSyData_Stop support.

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#824] opened 2020-07-03 09:51 UTC
It's often necessary to be able to reduce a profiling trace to a manageable size by only enabling profiling for e.g. a single time-step of a model run. For nvtx this requires calls to CUDA routines.

The Profiling API already has init() and shutdown() calls (which are currently unused in the nvtx wrapper). I propose to add the enable/disable calls into these wrapper routines although I'm slightly uneasy that I may be changing their expected semantics by doing that.

What do @hiker and @rupertford think?

**Comment by hiker** [comment] 2020-07-03 13:25
I was going to open a similar issue for KernelExtraction, since we typically only want to dump the data at a certain step - but thought that was not that urgent :)

I was going to suggest two solutions, which could become part of PSyData:
1) in the transform you could specify a `min` and `max` value. PSyData would increase a counter each time an instrumented region is executed. Only if the counter is between `min` and `max` would the code be executed (or alternatively, we could define `begin`, `end`, `step` similar to a loop, and only if `(counter-begin) % step==0`  and counter is between `begin` and `end` would the PSyData code executed.
2) a Fortran logical expression could be given to a transform. This would then be inserted into an `if` statement, and only if this expression evaluates to 'true' would the PSyData API be used. This could in theory allow tests like `if time==123 .and. myrank==32` - though of course the problem is how to get access to the time and rank (and whatever other variables the user might want to use) in the PSyLayer. Only option I see is to declare them input-parameter for a kernel (in which case PSyclone would pass the values into the PSy layer).

**Comment by hiker** [comment] 2020-07-03 13:38
Oh, otherwise while there is like no specification that the init and shutdown function should only be called once, it is the intention to be meant for this (e.g. in-situ visualisation might connect to the graphics backend). I would prefer to add separate PSyData_start and PSyData_stop functions if required.

**Comment by arporter** [comment] 2020-07-03 15:03
Yes, I thought there would be other use cases. In my particular case I don't think it's practical to assume that each individual PSyData call will have access to the necessary variables in order to decide whether or not to do something. Currently I manually modify the top-level, time-stepping routine to simply enable profiling at step `n` and disable it again at step `n+1`. I don't think there's any way of automating that since a human has to decide where to put those calls. Although we could put a counter inside instrumented regions, in general we have no idea how many times they're going to be called. I guess for dumping kernel data we could have a 'do it the first time only' type option.

**Comment by arporter** [comment] 2020-07-08 14:23
@hiker, would you mind taking a look at the change I've just committed and see whether you agree with my proposed changes/additions to the API?

**Comment by hiker** [comment] 2020-07-13 15:49
#837 merged.

**Comment by hiker** [comment] 2020-10-01 06:39
I'm reopening this, since not all psydata wrapper have support for this yet.

**Comment by hiker** [comment] 2020-10-01 06:40
#878 adds support for profiling library, outstanding is the code extraction library.

**Comment by hiker** [comment] 2020-10-27 00:51
This will be added as part of #955.

**Comment by hiker** [comment] 2021-04-19 07:00
The extraction library includes tests for ``is_enabled`` since #955, closing this issue.

**Closed by hiker** 2021-04-19 07:00 UTC
Labels: PSyData, enhancement, in progress
