### ISSUE TITLE
FortLineLength can make decisions that prevent nvidia's hpc sdk compiler from compiling code

### ISSUE THREAD

**Issue by LonelyCat124** [stfc/PSyclone#2248] opened 2023-08-07 14:57 UTC
I'm not sure what the exact behaviour is (@sergisiso may know more), but I have a replicator of behaviour leading to code that won't compile with nvidia's compiler, as it believes the line continuation symbols to be misplaced. This code:

```
def test_inline_if_ampersand(fortran_reader, fortran_writer):
    code = '''subroutine test()
    use external_module, only: some_type
    integer, dimension(:,:,:,:), allocatable :: pressure_prsc
    IF (.NOT. ALLOCATED(pressure_prsc))                                        &
      ALLOCATE(pressure_prsc        ( some_type%longstringname1,        &
                                      some_type%longstringname2,           &
                                      some_type%longstringname3, &
                                      some_type%longstringname4 ))
    end subroutine test
    '''

    psyir = fortran_reader.psyir_from_source(code)
    from psyclone.line_length import FortLineLength
    output = fortran_writer(psyir)
    print(output)
    print("---")
    line_length = FortLineLength()
    print(line_length.process(output))
    assert False
```

results in the following output:
```
subroutine test()
  use external_module, only : some_type
  integer, allocatable, dimension(:,:,:,:) :: pressure_prsc

  if (.NOT.ALLOCATED(pressure_prsc)) then
    ALLOCATE(pressure_prsc(1:some_type%longstringname1,1:some_type%longstringname2,1:some_type%longstringname3,1:some_type%longstringname4))
  end if

end subroutine test

---
subroutine test()
  use external_module, only : some_type
  integer, allocatable, dimension(:,:,:,:) :: pressure_prsc

  if (.NOT.ALLOCATED(pressure_prsc)) then
    &
&ALLOCATE(pressure_prsc(1:some_type%longstringname1,1:some_type%longstringname2,1:some_type%longstringname3,&
&1:some_type%longstringname4))
  end if

end subroutine test
```

What seems to happen is the line is truncated before the first statement, resulting in an empty line with an `&`. The NVIDIA compile will not compile with this empty line containing a line continuation symbol if its present, it will however compile if there is only
```
  if (.NOT.ALLOCATED(pressure_prsc)) then
ALLOCATE(pressure_prsc(1:some_type%longstringname1,1:some_type%longstringname2,1:some_type%longstringname3,&
&1:some_type%longstringname4))
  end if
```

It feels like creating an extra empty line for line continuation should not happen and that this is a bug?

**Comment by arporter** [comment] 2023-08-07 19:28
I think this is a duplicate of #1575?

**Comment by LonelyCat124** [comment] 2023-08-07 19:44
Yes, i may try to have a look tomorrow but if its difficult I'll have to leave it.

**Comment by arporter** [comment] 2023-08-14 14:39
Closing now #2250 is on master.

**Closed by arporter** 2023-08-14 14:39 UTC
Labels: bug, socrates
