### ISSUE TITLE
Update PSyclone to use new dl_esm_inf names

### ISSUE THREAD

**Issue by hiker** [stfc/PSyclone#198] opened 2018-07-26 05:42 UTC
In https://github.com/stfc/dl_esm_inf/pull/4#pullrequestreview-140583539 the public names were all changed to have a prefix of GO_.

PSyclone needs to be updated to use the new names:
- [x] the files included in tets/test_files/gocean1p0 that are from dl_esm_inf should be replaced with the latest version from dl_esm_inf
- [x] the test files need to be updated to use the new names (e.g. READ -> GO_READ, CT -> GO_CT, ...)
- [x] PSyclone (gocean1p0 I guess exclusively) needs to be updates

Calling this 'enhancement' for now - not sure if we need to do an official release of dl_esm_info before this should be changed? @arporter , @rupertford ??

**Comment by hiker** [comment] 2018-09-25 14:05
In theory this should be ready to go (branch new_dl_esm_info_version). It is already based on the "add-new-iteration-space" branch, so should go in after #215. But a few comments/discussions:

1) I have started to compile some of the test files. Which in turn means I had to add (nearly?) all mod files from dl_esm_inf. The side effect of this is now that testing takes a lot longer, since the PSyclone parser now traverses all those mode files, e.g.:
```
test_files/gocean1p0/compute_cu_mod.f90'
test_files/gocean1p0/argument_mod.f90'
test_files/gocean1p0/single_invoke.f90'
test_files/gocean1p0/global_parameters_mod.f90'      ! Start of dl_esm_inf files
test_files/gocean1p0/field_mod.f90'
test_files/gocean1p0/kind_params_mod.f90'
test_files/gocean1p0/region_mod.f90'
test_files/gocean1p0/halo_mod.f90'
test_files/gocean1p0/grid_mod.f90'
test_files/gocean1p0/subdomain_mod.f90'
test_files/gocean1p0/parallel_mod.f90'
test_files/gocean1p0/parallel_common_mod.f90'
```
The time reported by travis seems to have increased, too (though it varies quite a bit). So I am wondering, do we want to go this way, i.e. include all mod files? Should we 'fix' the parser to only parse directly included mod files (e.g. single_invoke only uses {kind_params, grid,field}_mod, everything else is from a use statement in one of those modules)? Should I fix up the remaining files as well (many still have the use statements commented out)?

2) I had to merge in the latest fparser (to get a parser fix), which then broke some of the unit tests. They are all fixed in this branch now.

**Comment by arporter** [comment] 2018-09-26 10:09
re. 1. - I don't understand why the tests are now a lot slower (I can reproduce that) since we do only parse the modules that contain kernels (line 1129 of `parse.py`). One of the advantages of fparser is that it doesn't recurse down into modules that are `use`d by the the current program unit.
 I would advocate stripping out as much as possible from the infrastructure files and putting them in a separate `infrastructure` directory - as is done for dynamo0.3. Alternatively, we could add dl_esm_inf as a git submodule. (We don't do it this way for dynamo0.3 because a) it's challenging for compilers and b) it's not in git.)

**Comment by hiker** [comment] 2018-10-01 05:49
Re. 1: I think you are mistaken: indeed, in parse.py only one module is loaded, but in statements.py around line 1175 (that's part of class UseStatement, function analyze()) it does load, parse, and analyze all modules, which basically recurses all the way across all dl_esm_info modules. And not only the modules declared in the 'interface' section (everything before 'contains'): when it parses subdomain_mod.f90, it will then find parallel_mod, which is only(!) used in the function decompose. So we parse truly everything, even modules used internally in some functions only.

Even worse: considering the following example:
```
  use kernel_mod, only : kern1, kern2, kern3
...
  call invoke(kern1(), kern2(), kern3())
```
Then for each of the three invokes kern1/2/3 all modules used in kernel_module will be parsed again(!) - and again recursing through all(!) modules. Reason is that the parsed modules are 'cached' in an attribute of the class Use (self.top.a.module) - since it creates a new instance of the Use class, it will parse all those files again. The attribute cache fine for module repeatedly encountered during parsing when using the same module file.

For example, my 'new_iteration_space.f90' test case which has the above  structures parses most (all?) of the dl_esm_inf modules three times!

So, I see 2.5 issues and solutions:
1) Fix PSyclone to 
    1) not parse all modules again if they have already been parsed. We might need some cleaning of the cache for test cases (though it is not actually the cache, it's the module attribute of the Use class)
    2) Do not parse 'secondary' modules? I am not 100% sure about this, since for proper testing that might actually be necessary.
2) Restructure dl_esm_info to avoid the usage of that many kernels. My suggestion would be that we introduce one psyclone_mod.f90 module that defines all(!) go* symbols. This module is then used by grid_mod, field_mod, ... everywhere. So ideally (I didn't try) this should not make any change to an application necessary (grid_mod imports psyclone_mod and makes all the symbols public etc). At the same time, all test_cases could only import psyclone_mod and compile (though probably not link). This would also address your second request, to either move the modules into an infrastructure directory, or use a submodule - we would be down to one file, would that be fine?

I don't think 1) should be addresses as part of this request, so feel free to open a ticket for that :)

I am happy to do 2), if you agree. This would also decouple dl_esm_inf and psyclone somewhat, since we would only have to share one module file.

**Comment by arporter** [comment] 2018-10-01 08:30
I think we are both right. The code does, as you say, look for modules and, if they're on the search path, it parses them. However, the search path is, by default, limited to the CWD and the directory containing the current source file. For dynamo0.3, the fact that the infrastructure files are in a different directory means that they are never parsed (I've stepped through  `FortranReaderBase.find_module_source_file()` in the debugger to verify this). Therefore, I think the best solution is to simply move the GOcean infrastructure modules into a separate directory.

**Comment by arporter** [comment] 2019-01-18 14:42
#223 was merged to master back in December. Closing this Issue.

**Closed by arporter** 2019-01-18 14:42 UTC
Labels: enhancement, in progress
