### ISSUE TITLE
[LFRic] Kernel meta data for mesh information

### ISSUE THREAD

**Issue by thomasmelvin** [stfc/PSyclone#18] opened 2017-03-29 09:42 UTC
LFRic ticket: https://code.metoffice.gov.uk/trac/lfric/ticket/983 Introduced adjacency information into the mesh that is required for certain boundary integral kernels.

Currently this information is extracted from the mesh in the psy layer and passed into the kernels.
At the moment these kernels are called through psykal lite partly because the metadata for passing adjacency information in does not exist.

It seems that this is part of a larger issue, how to pass mesh information into kernels?

It is proposed to include a new metadata type, mesh_data_type that would specify what mesh data is required in the kernel

This ticket is to implement the psyclone changes to support the proposed changes in  the realated lfric tickethttps://code.metoffice.gov.uk/trac/lfric/ticket/986

**Comment by TeranIvy** [comment] 2018-03-19 14:38
Support for extracting the mesh information is added in issue #59 (PR #136), which is currently being tested. After it is merged, it would be good to revisit this issue to see whether all the required mesh information is extracted or some further work is required.

**Comment by arporter** [comment] 2018-07-31 11:19
Closing as a duplicate of #150.

**Comment by TeranIvy** [comment] 2019-10-08 13:41
I am reopening the issue as it was suggested that the metadata for LFRic mesh entities are dealt with separately from the reference element (see e.g. review comments in #360).

**Comment by TeranIvy** [comment] 2020-03-11 11:11
The metadata design was outlined in PR #360. The specific comments are:
- [`meta_mesh` name](https://github.com/stfc/PSyclone/pull/360#discussion_r290286959) (seven metadata types in total),
- [mesh metadata](https://github.com/stfc/PSyclone/pull/360#discussion_r290287807) type,
- [`meta_mesh` contents](https://github.com/stfc/PSyclone/pull/360#discussion_r290377191) (contents and design).

**Comment by TeranIvy** [comment] 2020-03-11 11:45
LFRic examples are `gungho/source/kernel/_bd_` kernels for the metadata. PSy layer is in [psykal-lite](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/gungho/source/psy/psykal_lite_mod.F90).
The updated `rtheta_bd_kernel_mod.F90` in `examples/lfric/eg9` (PR #701) can be used in this issue.

**Comment by arporter** [comment] 2020-03-17 17:09
@TeranIvy or @thomasmelvin would you mind looking at the changes I've just made and checking that what I've said is true? In particular, which `nfaces` we use to dimension the array of adjacent faces. I think what I've written is consistent with the document you originally circulated but looking at https://code.metoffice.gov.uk/trac/lfric/ticket/1916 the situation might have changed?

**Comment by thomasmelvin** [comment] 2020-03-19 11:37
@TeranIvy should be able to give the definitive answer, but I think (and looking at [https://code.metoffice.gov.uk/trac/lfric/ticket/1916](url)) if face quadrature is required we pass in both the number of faces from the quadrature and also the number from the reference element if the meta data asks for it.

The way I view it is that the number from the quadrature is used for correctly dimensioning the arrays it passes, whilst the reference cell one is the correct mesh meta data value to use.

Hopefully this makes sense?

**Comment by TeranIvy** [comment] 2020-03-19 15:51
Sorry for not replying to this before, @arporter. Yes, the quadrature `nfaces_qr` is used for dimensions of basis and diff basis functions for face quadrature (similar to edge quadrature) and `nfaces_re` is for reference element and mesh meta data.
@thomasmelvin, I think that the `adjacent_face` only needs number of faces in the horizontal, hence the correct number of faces would be the horizontal faces from the reference element (see [`subroutine calc_face_id_in_adjacent_cell`](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/infrastructure/source/mesh/mesh_mod.F90#L2113) called by [`function get_adjacent_face(self) result (adjacent_face)`](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk/infrastructure/source/mesh/mesh_mod.F90#L2176)). Could you please confirm this?

**Comment by thomasmelvin** [comment] 2020-03-19 16:10
Thanks @TeranIvy, yes I agree, `adjacent_face` only needs the number of horizontal faces

**Comment by arporter** [comment] 2020-03-23 08:24
To clarify (and thinking about the kernel-stub generator), if a kernel requires `adjacent_face` *and* face quadrature then the extent of the `adjacent_face` array is declared to be the number of faces obtained from the face quadrature object. However, if the kernel does *not* require face quadrature, then the extent of the array is declared as the number of horizontal faces obtained from the reference element. (In both cases, we pass `nfaces_re_h` to the kernel.) Is that correct? I ask since it seems odd to me that we are changing the extent of the array depending on whether or not quadrature is supplied.

**Comment by thomasmelvin** [comment] 2020-03-23 09:38
@arporter I don't think that is quite right. I think that if the kernel asks for `adjacent_face` then the extent (== `nfaces_ref_h`) is obtained from the reference element.

If the kernel also asks for face quadrature then the extent (and number of faces it is computed on, say `nfaces_quadrature`) is obtained from the quadrature.

There is no requirement that both these numbers are same (though they often will be). If both `adjacent_faces` and `face_quadrature` are required then I think we pass in both numbers: `nfaces_ref_h` obtained from reference element and `nfaces_quadrature` obtained from the quadrature object

Does that sound sensible?

**Comment by arporter** [comment] 2020-03-23 10:02
> @arporter I don't think that is quite right. I think that if the kernel asks for `adjacent_face` then the extent (== `nfaces_ref_h`) is obtained from the reference element.
>
As in, this is *always*  the extent of the `adjacent_face` array? That seems to make more sense.

> If the kernel also asks for face quadrature then the extent (and number of faces it is computed on, say `nfaces_quadrature`) is obtained from the quadrature.
>
Are you talking about the extent and number of faces for the arrays related to the quadrature here (i.e. *not* the `adjacent_face` array).

> There is no requirement that both these numbers are same (though they often will be). If both `adjacent_faces` and `face_quadrature` are required then I think we pass in both numbers: `nfaces_ref_h` obtained from reference element and `nfaces_quadrature` obtained from the quadrature object
>
Sure, I'm happy to treat the two 'number of faces' entities entirely separately.

**Comment by thomasmelvin** [comment] 2020-03-23 11:06
> As in, this is _always_ the extent of the `adjacent_face` array? That seems to make more sense.
Yes

> Are you talking about the extent and number of faces for the arrays related to the quadrature here (i.e. _not_ the `adjacent_face` array).
Yes

> Sure, I'm happy to treat the two 'number of faces' entities entirely separately.
I think this is a sensible idea, what do you think @TeranIvy?

**Comment by TeranIvy** [comment] 2020-03-23 11:10
> 
> > Sure, I'm happy to treat the two 'number of faces' entities entirely separately.
> 
> I think this is a sensible idea, what do you think @TeranIvy?
>
Agreed, @thomasmelvin .

**Closed** 2020-05-07 15:28 UTC
Labels: LFRic, in progress
