### ISSUE TITLE
Support gh_shape=gh_evaluator

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#52] opened 2017-07-04 16:17 UTC
Currently PSyclone only supports gh_shape = gh_quadrature_xyoz. In this issue we will add support for
gh_shape = gh_evaluator. This was originally ticket 942 on the SRS.

**Comment by arporter** [comment] 2017-07-05 09:00
@ss421 Steve, am I right in  thinking that we no longer pass in any additional args from the Algorithm layer when a kernel needs basis/diff basis functions? Currently PSyclone expects there to be a 'qr' argument if a kernel requires quadrature.

**Comment by ss421** [comment] 2017-07-05 09:26
There maybe some confusion - previously evaluators and quadrature were bundled together using inheritance. quadrature was an extension of evaluator. However, evaluator has now been removed so there is no longer an evaluator object to pass from the Algorithm layer.

To summarise:

1. For kernels that require quadrature, then a quadrature object (qr) is required. An example is density_update_alg_mod.x90 which calls the following invoke:

call invoke( rrho_kernel_type( div_temp, mass_flux_mult, qr ) )

2. For kernels that require evaluator, there are no additional objects (qr not required). An example is init_prognostic_fields_alg_mod.x90 which calls the following invoke:

call invoke_initial_theta_kernel( theta, chi )

which is currently psykal-lite awaiting the changes in this ticket.

**Comment by arporter** [comment] 2017-07-05 11:03
Aha, that's clear. Thanks.

**Comment by arporter** [comment] 2017-07-07 12:54
Hi again @ss421 - looking at the example code in SRS 942:

    ! Get the nodes and number of degrees of freedom from the write field
    ndf_nodal  = w0_field_proxy%vspace%get_ndf()
    nodes => w0_field_proxy%vspace%get_nodes()

    ! w0 GH_BASIS
    ndf_w0  = w0_field_proxy%vspace%get_ndf( )
    dim_w0  = w0_field_proxy%vspace%get_dim_space( )
    allocate( basis_w0(dim_w0, ndf_w0, ndf_nodal) )
    do df_nodal = 1, ndf_nodal
      do df_w0 = 1, ndf_w0
          basis_w0(:,df_w0,df_nodal) =  w0_field_proxy%vspace% &
              evaluate_function(BASIS,df_w0,nodes(:,df_nodal))
      end do
    end do

I see that the field being written to is the one used to get the nodal points. Does this then mean that a kernel that requires an evaluator must only write to a single field argument?

**Comment by ss421** [comment] 2017-07-07 14:07
Hi @arporter, that is my understanding but I'd like to double check with Tom - those examples were generated with help from Tom so I'd also like to clarify that there correct. 

Also, looking at the second basis evaluation in SRS 942 and current psykal-lite code (e.g. invoke_initial_theta_kernel), I'm not sure it is necessary to evaluate 'diff_basis_w1'. I'll also check that with Tom.

Cheers, Steve

**Comment by ss421** [comment] 2017-07-10 09:44
In response to my previous comment - Tom has confirmed: 

i) that each kernel will write to only one field, and
ii) that the example code provided on SRS 942 is correct.

Cheers

Steve

**Comment by arporter** [comment] 2017-07-21 08:14
Realised that if a kernel wrote to an operator then it wasn't clear whether we should evaluate the basis functions on the nodes of the to- or from-space. @thomasmelvin has clarified:
"I would say for an operator which uses an evaluator the default would be that it would evaluate any basis functions on the nodes of the space that the operator maps to. This would be the equivalent of using the function space of the field that is written to in a standard kernel."

**Comment by arporter** [comment] 2017-07-21 16:20
I think the basic functionality is now complete. Next steps are:

- [ ] Check that the generated code compiles
- [ ] Check that PSyclone plays nicely with LFRic 
- [ ] Implement the necessary extensions to the kernel-stub generator
- [ ] Test the kernel-stub generator

**Comment by arporter** [comment] 2017-07-24 15:38
Generated code does not compile because basis/diff basis arrays are declared as rank 4 instead of rank 3.

**Comment by arporter** [comment] 2017-07-25 08:56
Code now compiles (or would do if my fake LFRic infrastructure had all the necessary bits in it).
@ss421 - please could you try this branch (`evaluator`) with LFRic now? I think @TeranIvy has documented how to do this with the updated structure of PSyclone (it's different to the version currently used on the trunk of LFRic).

**Comment by arporter** [comment] 2017-07-31 11:43
I forgot to say that the branch for this work is `evaluator`!

**Comment by arporter** [comment] 2017-08-30 14:23
Hi @ss421 have you had a chance to re-check this branch with LFRic since I did the above fix? (I thought I'd sent you an email but cannot find any trace of it so apologies if not.) You may need help from @TeranIvy in getting PSyclone installed as she's been having a lot of difficulties on the MO machines.

**Comment by ss421** [comment] 2017-08-30 15:44
Hi @arporter, I had a number of issues running it but these have all been sorted now + I've been on holiday and only returned to work yesterday so catching up. I have now tested this version of PSyClone with the current head of trunk (yesterday) and it has run. I have not tested the evaluator functionality yet - that's my next plan.

I should note that one of the issues relates to the change in name of a built in from divide_field to inc_divide_field. Assuming that this works fine for evaluators, there will need to be a change in dynamo with implementation of this PSyClone (@TeranIvy / @arporter ?). 

Cheers

Steve

**Comment by ss421** [comment] 2017-08-30 15:45
Hi @arporter, I had a number of issues running it but these have all been sorted now + I've been on holiday and only returned to work yesterday so catching up. I have now tested this version of PSyClone with the current head of trunk (yesterday) and it has run. I have not tested the evaluator functionality yet - that's my next plan.

I should note that one of the issues relates to the change in name of a built in from divide_field to inc_divide_field (@TeranIvy helped with that). Assuming that this works fine for evaluators, there will need to be a change in dynamo with implementation of this PSyClone (@TeranIvy / @arporter ?).

Cheers

Steve

**Comment by ss421** [comment] 2017-08-30 17:01
Hi @arporter,

Ive just tested this version of psyclone with an evaluator invoke:

si_operators_alg_mod.x90 uses evaluators and has a psy-lite implementation. So for a first test I tried using the PSyClone invoke rather than the psy-lite version 'call invoke ( sample_flux_kernel_type( rho_at_u, ones, w2_rmultiplicity, rho) )'. I get the following error:

raise DatabaseException( message.format( unit, prerequisite ) )
DatabaseException: Program unit "si_operators_alg_mod_psy" requires "evaluate_function_mod" but it was not found in the database

I assume this is a psyclone error?

I also compared the auto generated code with the psy-lite version. Other than name convention they appear to be identical except the third and forth arguments of 'sample_flux_code' are flipped - I guess this is an issue with psy-lite/kernal args rather than PSyClone? I assume the rule is the argument order in the kernel code follows that in the psy-layer call.

Cheers

Steve

**Comment by TeranIvy** [comment] 2017-08-30 17:25
Hi @ss421,

The built-in name change from `divide_field` to `inc_divide_field` in dynamo depends on whether the issue #61 (pull request #71, reviewed by @arporter ) is implemented in PSyclone before the next release. If it is then all built-ins will have to be renamed in dynamo, not just this one. I have an LFRIc ticket for that (1174) and everything works with my local PSyclone installation from the branch. However, as @arporter said, I have issues in running Rose stem tests with the appropriate PSyclone branch installations on Spice and Cray (XC40). For now it looks that the error stems from our outdated Python environment and this will have to be updated. I will be quite busy for the next two weeks (ESCAPE workshop in Poland and then SciCADE conference in Bath) so I will not be able to properly prepare a new PSyclone environment before 18 September.

**Comment by arporter** [comment] 2017-08-31 08:42
Hi @ss421, thanks for testing this. That database error must be something to do with the build system - PSyclone doesn't do anything with databases. I'll have a look at the argument order for `sample_flux_code` and get back to you.

**Comment by arporter** [comment] 2017-08-31 08:59
Hi @ss421, the 3rd and 4th args to `sample_flux_code` are both fields and therefore, as you say, their order is determined by the order with which they are specified in the invoke. As long as that is true here then PSyclone is doing what it is supposed to.

**Comment by ss421** [comment] 2017-08-31 09:20
Hi @TeranIvy: Ok thanks for update. There will be no required dynamo changes for the functionality provide in PSyClone for evaluators. Once its available - post Sept 18th I will update dynamo to use it, meanwhile I will check that the evaluators work in my branch.

Hi @arporter: Ok thanks - it appears that the page was outdated since I removed the evaluator object. so I've updated it the page (see diff on MOSRS #942). In summary:


A.
instead of:
`use evaluate_function_mod, only : BASIS, DIFF_BASIS`
it should be
`use function_space_mod,    only : BASIS, DIFF_BASIS`

B.
instead of:
`w0_field_proxy%vspace%evaluate_function(BASIS,df_w0,nodes(:,df_nodal))`
it should be 
`w0_field_proxy%vspace%call_function(BASIS,df_w0,nodes(:,df_nodal))`

C.
instead of:
`diff_basis_w1(:,df_w1,df_nodal) = w1_field_proxy%vspace%evaluate_function(DIFF_BASIS,df_w1,nodes(:,df_nodal))`
it should be 
`diff_basis_w1(:,df_w1,df_nodal) = w1_field_proxy%vspace%call_function(DIFF_BASIS,df_w1,nodes(:,df_nodal))`

Also, allthough it probably doesn't matter, in cases where the `GH_DIFF_BASIS` or `GH_BASIS` are not present, I don't think its necessary to include the related enumerator from function_space_mod.

**Comment by ss421** [comment] 2017-08-31 09:20
@arporter: OK thanks - Ill change dynamo accordingly.

**Comment by arporter** [comment] 2017-08-31 09:59
Thanks Steve. I've re-named `evaluate_function` and changed to using `function_space_mod`. Is everything now OK as far as you're concerned?

**Comment by arporter** [comment] 2017-08-31 10:00
(I've elected to be lazy/keep things simple and just do `USE function_space_mod, ONLY: GH_BASIS, GH_DIFF_BASIS` even when only one of them is required.)

**Comment by ss421** [comment] 2017-08-31 10:43
Hi @arporter,

Thanks - yes that appears to work for this kernel even though I didn't switch the order of the arguments - I'm just testing on desktop though. So I would assume all is well with the PSyClone change. 

I will test the remaining evaluators so that I'm ready to implement when its available in September. Ill report back after I have tested the remaining kernels that use evaluators.

Thanks, Steve

**Comment by ss421** [comment] 2017-08-31 10:44
Is there a way to reply to a particular comment on here - so that the context is clear?

Thanks, Steve

**Comment by rupertford** [comment] 2017-10-02 15:20
pr #60 has been merged to master. Closing this issue.

**Closed by rupertford** 2017-10-02 15:20 UTC
Labels: enhancement
