### ISSUE TITLE
Quis custodiet ipsos custodes? (Improve test coverage of test infrastructure code.)

### ISSUE THREAD

**Issue by arporter** [stfc/PSyclone#1199] opened 2021-04-09 10:08 UTC
#1194 demonstrates that some of the test infrastructure code (related to the compilation testing for the GOcean and LFRic APIs) is not covered by the test suite. This issue will extend the existing tests in `utilities_test.py` to cover this code (as far as is possible).

**Comment by arporter** [comment] 2021-06-30 08:04
We could also do with adding a bit of 'logging' to the compilation testing infrastructure to record when e.g. we fail to find a file.

**Comment by hiker** [comment] 2022-09-16 13:28
Duplicate of #1861. The logging for missing files is happening (needs to use `-s` in pytest, which (unfortunately) also reports any infrastructure file as missing, since they are provided pre-compiled, but the information required for debugging is certainly there.

**Closed by hiker** 2022-09-16 13:28 UTC
