### ISSUE TITLE
ArrayRangeToLoop might incorrectly assume full range

### ISSUE THREAD

**Issue by nmnobre** [stfc/PSyclone#2028] opened 2023-01-30 11:48 UTC
When processing ECMWF's NEMO code, I came across an issue in `trc_oce.f90`.
Indeed, it'd seem that:

```
prgb(:,:) = zrgb(2:4,:)
```

is being transformed to and replaced by:

```
!$omp parallel default(shared), private(idx,idx_1)
!$omp do schedule(static)
do idx = LBOUND(prgb, 2), UBOUND(prgb, 2), 1
  do idx_1 = LBOUND(prgb, 1), UBOUND(prgb, 1), 1
    prgb(idx_1,idx) = zrgb(idx_1,idx)
  enddo
enddo
!$omp end do
!$omp end parallel
```

**Comment by LonelyCat124** [comment] 2024-05-02 12:32
I think this is a duplicate of issues mentioned in #1841 (second comment)

**Comment by sergisiso** [comment] 2024-05-28 12:00
I am fixing this in #1841

**Closed by sergisiso** 2024-05-28 12:00 UTC
Labels: bug, NEMO
