### ISSUE TITLE
Add r_tran_operator_types

### ISSUE THREAD

**Issue by BShipway** [stfc/PSyclone#1999] opened 2023-01-05 12:32 UTC
In the same way that r_solver_operator_types contain data of type r_solver, r_tran_operator_types contain data that is of type r_tran.  r_tran_operators need to be added to the  LFRicConstants.DATA_TYPE_MAP.

**Comment by TeranIvy** [comment] 2023-01-05 12:34
Closing as duplicate of #1998

**Closed by TeranIvy** 2023-01-05 12:34 UTC
