### ISSUE TITLE
Potential problem with installation of PSyclone on a Mac using pip

### ISSUE THREAD

**Issue by deardenchris** [stfc/PSyclone#861] opened 2020-07-23 15:28 UTC
When attempting to install PSyclone on my Mac using pip, I noticed that the `examples` directory didn't get created within `share/psyclone` as it should do; only `psyclone.cfg` is present (see below). As a workaround, I was able to use `python setup.py install` instead and this created the `examples` directory successfully. 

At this stage I can't be sure if this is merely a problem with the particular instance of pip that I am using. It would be useful if another Mac user was able to test the installation using pip to see if the issue is reproducible or not. 

`chrisdearden@deardenhost:~/git_repos/PSyclone$ pip3 uninstall psyclone`
`WARNING: Skipping psyclone as it is not installed.`
`chrisdearden@deardenhost:~/git_repos/PSyclone$ pip3 install .`
`Processing /Users/chrisdearden/git_repos/PSyclone`
`Requirement already satisfied: pyparsing in /Users/chrisdearden/Library/Python/3.7/lib/python/site-packages (from PSyclone==1.9.0) (2.4.7)`
`Requirement already satisfied: fparser==0.0.11 in /Users/chrisdearden/Library/Python/3.7/lib/python/site-packages (from PSyclone==1.9.0) (0.0.11)`
`Requirement already satisfied: configparser in /Users/chrisdearden/Library/Python/3.7/lib/python/site-packages (from PSyclone==1.9.0) (5.0.0)`
`Requirement already satisfied: six in /Users/chrisdearden/Library/Python/3.7/lib/python/site-packages (from PSyclone==1.9.0) (1.15.0)`
`Building wheels for collected packages: PSyclone`
`Building wheel for PSyclone (setup.py) ... done`
`Created wheel for PSyclone: filename=PSyclone-1.9.0-cp37-none-any.whl size=521164sha256=fc1efb0a9d48bea4015d10901087cb5c7184191d6bc399abbf92228cd3dcc48d Stored in directory: /private/var/folders/cc/ts0__ln96019z_brslqngky80000gq/T/pip-ephem-wheel-cache-ov15rft6/wheels/e6/30/ff/b02f8c49889d1e8c711f8ee3d63bb7ede0cb95fe7076c32e71`
`Successfully built PSyclone`
`Installing collected packages: PSyclone`
`Successfully installed PSyclone-1.9.0`
`chrisdearden@deardenhost:~/git_repos/PSyclone$ ls -lrt /usr/local/share/psyclone/`
`total 8.0K`
`-rw-r--r-- 1 chrisdearden 7.0K Jul 23 11:22 psyclone.cfg`

**Comment by arporter** [comment] 2020-07-23 16:29
I know @christophermaynard is also on the Dark Side. Can you reproduce this on your mac Chris?

**Comment by TeranIvy** [comment] 2020-07-23 19:18
I got an email today from @BShipway about one of his students having issues with installation of PSyclone on Mac.

**Comment by rupertford** [comment] 2020-07-23 21:55
Would be good to know what the problem is @TeranIvy. As more turn to the dark side it might be useful to have some vader-specific instructions in the user guide if there are certain common problems.

**Comment by christophermaynard** [comment] 2020-07-24 07:48
Hmm... I don't see that problem. I have the examples for a "system" install and a user install. I am using the following version.
`pip --version
pip 19.3.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)`

**Comment by deardenchris** [comment] 2020-07-24 12:19
Thanks Chris for testing. Interesting as I am using the exact same version of pip. For me it only generates psyclone.cfg in /usr/local/share/psyclone. Do you see the examples directory as well in this same location? I'm wondering if I might be looking in the wrong place

**Comment by TeranIvy** [comment] 2020-07-24 13:17
Just heard back from Ben's student. Her issue was related to having both Python 2 and 3 and `pip install` defaulted to Python 2. She says that using `pip3` resolved the issue. Different Python versions/installations on the same system don't play nicely together, as we discovered in the Met Office 😃 They can be managed via `virtualenv`s and environment variables but it's tricky...

**Comment by rupertford** [comment] 2020-07-24 23:56
For the time being I've created a [wiki page](https://github.com/stfc/PSyclone/wiki/Installation-Issues) to capture issues to do with installation. We can decide whether we want a FAQ, information in the user-guide or something else at a later date. I just wanted to store the information somewhere other than in an issue.

**Comment by arporter** [comment] 2024-03-22 13:40
We've not touched this in 3.5 years so I'll close it for now.

**Closed by arporter** 2024-03-22 13:40 UTC
Labels: bug
