### ISSUE TITLE
OpenACC reduction clause

### ISSUE THREAD

**Issue by jwallwork23** [stfc/PSyclone#2436] opened 2023-12-13 11:42 UTC
In the latest version of our PSyclone-driven OpenACC GPU port, reduction loops get `loop seq`. Performance is improved significantly if these are manually edited to instead use `loop independent reduction(...)`. Would it be possible to support `reduction` clauses in PSyclone?

**Comment by arporter** [comment] 2023-12-13 11:49
Yes, we definitely need to do this. I'm going to close this as a duplicate of #514 but I've added your text there.

**Closed by arporter** 2023-12-13 11:49 UTC
Labels: enhancement, question
