### ISSUE TITLE
Failing markdown-link-check on CI

### ISSUE THREAD

**Issue by TeranIvy** [stfc/PSyclone#1610] opened 2022-02-07 17:57 UTC
Markdown link checks reports dead links to Jupyter notebooks. Grepping for them returns the locations listed below. Assigning @arporter and myself, as @arporter added the notebooks (I'd be happy to fix this if I know where to look 😄 ).

```
README.md:19: * [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/stfc/psyclone/master?filepath=examples%2Fnemo%2Feg4%2Fcopy_stencil.ipynb) Uses PSyclone's NEMO API to process some simple Fortran code, display the resulting PSyIR and then re-generate Fortran.
README.md:21: * [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/stfc/psyclone/master?filepath=examples%2Fgocean%2Feg1%2Fopenmp.ipynb) Uses PSyclone's GOcean API to process example code that conforms to the PSyKAl separation of concerns. Transformations are applied in order to fuse various loops before parallelising the result with OpenMP.
README.md:23: * [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/stfc/psyclone/master?filepath=examples%2Fgocean%2Feg1%2Fdag.ipynb) demonstrates the generation of a DAG for the PSy layer of the previous example.
README.md:29:[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/stfc/psyclone/master?filepath=tutorial%2Fnotebooks%2Fintroduction.ipynb).
doc/user_guide/tutorial.rst:44:`<https://mybinder.org/v2/gh/stfc/psyclone/master?filepath=tutorial%2Fnotebooks%2Fintroduction.ipynb/>`_.
```

**Comment by arporter** [comment] 2022-02-07 21:36
This is just a timeout/problem with MyBinder. After several attempts tonight I've succeeded in getting those links to work. When it didn't work I mostly saw Internal Server Error (500) which doesn't help much. It may be worth checking to see what configuration options the markdown link checker offers.

**Comment by arporter** [comment] 2022-02-24 08:56
Closing this as it's not a bug - just an issue with websites that are sometimes slow to respond.

**Closed by arporter** 2022-02-24 08:56 UTC
Labels: bug
